#+TITLE: Containment

Containment is a candidate for a "table of transcendental [[https://monoskop.org/Cultural_techniques][techniques]]".

* TODO The Concept of Containment
#+BEGIN_QUOTE
contain (v.)

c. 1300, "restrain (someone), control (oneself), behave (in a certain way),"
from Old French contein-, tonic stem of contenir, from Latin continere
(transitive) "to hold together, enclose," from assimilated form of com "with,
together" (see con-) + tenere "to hold," from PIE root *ten- "to stretch."

From mid-14c. as "to have (something) as a constituent part;" from late 14c. as
"have something inside, enclose."

([[https://www.etymonline.com/word/contain#etymonline_v_18267][etymonline]])
#+END_QUOTE

The concept of containment is powerful and rudimentary. Roughly, /containment/
seems to be the concept that distinct things can be gathered and held together
by some other thing, and thereby treated as one. It is difficult to determine
whether we can /think/ at all without presupposing this concept. The modern
concept of /concept/ seems to presuppose the technique of containment, and I
wager that the concept of /collection/ is abstracted from groupings enabled by
the technique of containment. I guess most animals don't have access to this
technique, or else we'd often see them toting valuables in makeshift bags and
boxes.

* Containerization

(With an eye towards the software technique.)

Container ships yielded exponential increase in shipping capacity. But it's this
actually the capacity we need?

What is the real need? Was it greater quantity of stuff sent quicker? Or is the
real need not rather more careful allocation of resources, better routing and
better fundamental design?

The capacity for massive throughput creates an inertial force tending a
structure towards quicker consumption and increased volumes of production.

What of all the space and time wasted by those things manufactured in order to
keep up the throughput and countless corners left empty my round cargo in
rectangular containers?

* The Inventory Management Game: Bags, Togetherness, and Cultural Techniques

Containers (pockets, bags, boxes, tins, gourds, jugs, cabinets, etc.) are
so ubiquitous that very few of us appreciate how revolutionary and
indispensable the technology is.

** References:
- https://dpadblog.com/2013/12/11/the-8-rules-of-rpg-inventory-management-and-how-they-apply-to-life/
- https://aaai.org/ocs/index.php/AIIDE/AIIDE17/paper/viewFile/15899/15226
- http://tobolds.blogspot.com/2009/05/inventory-management.html

** re:
- [[https://bluebottlegames.com/games/neo-scavenger][NEO Scavenger]]
- Togetherness
- Cultural Techniques
