#+TITLE: Ideals

I'm inclined to develop understanding and voice views from an idealistic
perspectives, but I hope not to be dogmatically fixated on the corresponding
ideology.

I hope to collaborate on the millennia-long project of cultivating a
radical, emancipatory, sustainable, concernful, thoughtful, being within the
world.

What we do, and do not, should be in consideration of the shape our actions will
take over the course of the longest imaginable run.

The only way to aim our actions over these timescales is to keep /ideal limits
in view/.  But, of course, to live and work in the world requires more immediate
action, and many decisions must made on shorter terms.

There is a constant tension to balance: on one side, the regulative force of the
ideal envisioned at the eventual limit; on the other, the exigencies of the
moment that conceal and present the immanent possibilities we can actualize.

By definition, the pragmatic choices made to meet the needs of the moment will
not actualize the ideal. This does not mean they are "defective"! However, this
does not excuse acting thoughtlessly or without need. It does not justify
the selection of subpar alternatives to meet a short-sighted vision.

#+begin_quote
... harmonize right and wrong  and rest in the balance of nature. This is called
taking both sides at once.

[cite:@zhuangzi08_chuan_tsu]
#+end_quote


#+PRINT_BIBLIOGRAPHY:
