#+TITLE: Rhythm

#+begin_quote
If life is not always poetical, it is at least metrical.  Periodicity rules over the mental experience of man, according to the path of the orbit of his thoughts.  Distances are not gauged, ellipses not measured, velocities not ascertained, times not known.  Nevertheless, the recurrence is sure.  What the mind suffered last week, or last year, it does not suffer now; but it will suffer again next week or next year.  Happiness is not a matter of events; it depends upon the tides of the mind.

[cite:@meynell1896rhythm]
#+end_quote

* Meditation

Find the fixpoint of thoughtful being by relaxing into the rhythm of
communication's constitutive continuities.

Abide in the eternal recurrence, becoming being in the communication of care.

* Practice

Knowing my rhythm, it can be used: when I'm up, I can throw myself into the
work, and just let myself be carried away by it. When I'm down, I can use the
negative polarity of it to (constructively) critique what I did before, to
identify short-comings and have some fruits that will guide improved work on
the next cycle. And rest! Don't forget to rest.

* Questions and quips

Characterizations of the infinite in terms of periodicity: do they admit of any
periodic recurrence? And if so, to what degree?

An infinite so variegated that any recurrence is impossible in principle could
seem horrifying, as perhaps the pure form of cosmic horror. This would be
Peirce's principle of firstness, but modified such that no "evolutionary love"
were possible: the emergence of a pattern, habit, and routine ruled out. This is
also Wittgenstein's nightmare of an absolutely unruly (_un*regel*mäßig_) way of
life.

Can we define equality starting in terms of fixed points?


#+PRINT_BIBLIOGRAPHY:
