#+title: Poems
#+author: Shon Feder

Not only not judgments (/Urtheil/), but not necessarily even content (/inhalt/).
So are these constellations of terms judgeable? I'd not volunteer to submit them
to judgment.

But, even if only what is claimed to have content should be judged, I suppose
even the uncontented can be shared.

* Poems
** Rough Century
/2025 - Late Summer/

#+BEGIN_EXAMPLE
This
  Dwelling                       (with-)?
  standing
  roughly

one
  Century

roughly
as in-
  conceivable
as a

Life,
  which,

in comprehending,
we began
  to mourn:
that they are all Ways
all ready all

dying.
  The

World is dying:
( 
  in monochrom

    wringing out
  Extractions
    winding down
  mechanized
    Work to the
  grasping drains
|
  in technicolor

    co-terminal initials
  illiminating 'an image of the world
      in which the continuous is
      an autonomous notion'[1]
    and co-continuous punctuations
  unfolding our singular zeros
      form paths, becoming
      for others, what will have been 
).

May we live,
  roughly spanning
  our Centuries,

let us share,
  weather wearing
  us into worn,

A
 World

-- We will
 have been
   as These
: All
      flowing
 Each
      thru out
  One
      another
     .
     
#+END_EXAMPLE

[1] Karl Popper, on C. S. Peirce, quoted in "Charles Sanders Peirce: A Life", p. 6.

** Being Meanings
/Summer 2025 - Winter 2026/

#+begin_example
Since, in being,
  we aspire to live
  in the appearance
     of sun & sign
just, as meanings,
  we transpire to pass
  thru the transpearance[1] 
     of air & sense,

We must subject others
  thru sensible communication

with no less care

than we submerge our selves
  in material environments.
#+end_example

[1] "In this case, though, in which transparence takes on a surprisingly
affirmative valence, we must be willing to hear transparence not as grasping,
comprehending or peering through— transparency—but rather as “trans-pearance,”
the horizontal movement of presences and meanings in the system of Relation."
("POETRY OF RELATION: ÉDOUARD GLISSANT, FRENCH MODERNISM, AND THE POETICS OF
OPACITY", Neal Alfred Allar,
https://ecommons.cornell.edu/server/api/core/bitstreams/8121d334-1744-4288-8a71-6eb34b3fb2b6/content)

* Scraps

In terminal times a mind turns over terms at all times.
