#+TITLE: Quips

Things To be sorted and/or expanded or deleted...

* The formal paradoxes of the early 20th century
I suspect that a common root of these was the use of /general logic/ as an
*organon*. In Kant's critical philosophy, he admonishes against this,
warning that will produce monstrous results.

To use logic as an organon is to use it to extend our knowledge. That is
done whenever we try to reason from purely general logical principles to
existence of any sort. This occurs in the axiom of unrestricted
comprehension.
* We are so nearsighted
It is hard to comprehend how far ahead the vision of theoretical visionaries
reached. Every day, arenas for idle chatter (like Reddit, Hacker News, and
Lobste.rs) are awash in "new" "ideas" (actually /relabeled concepts/) and
"novel" "insights" (actually /novelty framings/). But Plato already foresaw how
writing would erode memory, Leibniz foresaw the automation of proof and
ratiocination, Hobbes articulated the core notions of cybernetics, Cantor
described the basic technique needed for music visualizers -- I could go on and
no, and would only be limited by the meagerness of my education.
* We deserve to live well
Humanity as a whole does not seem to believe that it deserves to live well. We
must become convinced that we deserve to live well so that we become compelled
to form our communities to serve this end.
* Masquerading as kindness
Forms of compliance and complicity masquerade as kindness.
* Wild guesses
- Girard's cite:girard11 culminates in a formal theory of /transcendental
  inter-subjectivity/.
* Atomic individuality
Atomic individuality and absolute independence are illusions born of the
misapplication of pure reason. An atomic individual with total independence is
not a possible object of cognition.

This fantasy (really a "nightmare of reason") can entertain lifestyle
anarchists, ancaps, and neoliberals only because they suppress the necessary
context in which humans must come into being.
* Pattern matching is in tension with representation independence
Pattern matching is lovely. I'd strongly encourage anyone who hasn't played with
a language supporting pattern matching to do so ASAP. As a matter of fact, skip
straight to unification. However, <something about tension with abstraction>.

The very premise of pattern matching is that the surface representation of a
structure can be used as an *iconic* interface to its components. <explain
iconic>.


Pattern matching lets us access arbitrarily nested components of data by
matching an instance of the data against a schematic form of it, with free
variables located at situations where we'd will find the components we want to
extract.

This places naive pattern matching in direct opposition to *representation
independence*.
* Melting
#+BEGIN_VERSE
My mother,
striving to live a life she felt to be free,
conceived a cage of a novel
kind to me.
#+END_VERSE
* Nutshelled
** Virtual Machines vs. Containers
VMs use an abstraction of machine hardware to run real OSes on the host machine.
Containers use an abstractions of an operating systems to run programs in the
host operating system.


bibliography:../../bibliography/references.bib
