#+TITLE: Quips

Things To be sorted and/or expanded or deleted...

* The formal paradoxes of the early 20th century
I suspect that a common root of these was the use of /general logic/ as an
*organon*. In Kant's critical philosophy, he admonishes against this,
warning that will produce monstrous results.

To use logic as an organon is to use it to extend our knowledge. That is
done whenever we try to reason from purely general logical principles to
existence of any sort. This occurs in the axiom of unrestricted
comprehension.
* The Inventory Management Game: Bags, Togetherness, and Cultural Techniques
Containment is a candidate for transcendental techniques.

Containers (pockets, bags, boxes, tins, gourds, jugs, cabinets, etc.) are
so ubiquitous that very few of us appreciate how revolutionary and
indispensable the technology is.
** References:
- https://dpadblog.com/2013/12/11/the-8-rules-of-rpg-inventory-management-and-how-they-apply-to-life/
- https://aaai.org/ocs/index.php/AIIDE/AIIDE17/paper/viewFile/15899/15226
- http://tobolds.blogspot.com/2009/05/inventory-management.html
** re:
- [[https://bluebottlegames.com/games/neo-scavenger][NEO Scavenger]]
- Togetherness
- Cultural Techniques
* We are so nearsighted
It is hart to comprehend how far ahead the vision of our theoretical visionaries
reached. Every day, arenas for idle chatter (like Reddit, Hacker News, and
Lobste.rs) are awash in "new" "ideas" (actually /relabeled concepts/) and
"novel" "insights" (actually /novelty framings/). But Plato already foresaw how
writing would erode memory, Leibniz foresaw the automation of proof and
ratiocination, Hobbes articulated the core notions of cybernetics, Canto
described the basic technique needed for music visualizers -- I could go on and
no, and would only by limited by the meagerness of my education.
* We deserve to live well
Humanity as a whole does not seem to believe that it deserves to live well. We
must become convinced that we deserve to live well so that will demand that our
communities be structured to meet this demand.

* Masquerading as kindness
Forms of compliance and complicity masquerade as kindness.
* Wild guesses
- Girard's cite:girard11 culminates in a formal theory of /transcendental
  inter-subjectivity/.
* Nutshelled
** Virtual Machines vs. Containers
VMs use an abstraction of machine hardware to run real OSes on the host machine.
Containers use an abstractions of an operating systems to run programs in the
host operating system.


bibliography:../../bibliography/references.bib
