#+TITLE: Reading List
#+OPTIONS: toc:3

This page documents things I have read (since <2018-04-08 Sun>), and things I
intend to read in the coming months (and years).

* Currently Reading
** The Blind Spot
   (ref: cite:girard11)

   [[file:reading-notes/girard-the-blind-spot.org][Notes]]
** An Introduction to Mathematics
   (ref: cite:whitehead93)

   [[file:reading-notes/whitehead-introduction-to-mathematics.org][Notes]]
** Software Foundations: Logical Foundations
   (ref: cite:Pierce:SF)

   [[file:reading-notes/pierce-software-foundations-logical-foundations.org][Notes]]
** Miscomputation in Software: Learning to live with errors
   (ref: cite:Petricek_2017)


* Will Read
  Texts in this list are not being actively read, but they may have been started
  or partially read. They are, in any case, yet to be completed.
** Logic -> TypeTheory+
   Listed in approximate order of ascent.
*** On Axiomatic Systems for Arbitrary Systems of Sentences
    (ref: cite:hertz12_axiom_system_arbit_system_senten)
*** Investigations into Logical Deduction
    (ref: cite:m.69_gerhar_gentz_german)
*** Natural Deduction
    (ref: cite:dag06_natur)
*** Intuitionistic Type Theory
    (ref: cite:martin1984intuitionistic)
*** Type Theory and Formal Proof
    (ref: cite:rob2014type)
** (Abstract) Algebra -> Topology+
   Listed in approximate order of ascent.
*** Experiments in Topology
    (ref: cite:barr89_exper)
*** Conceptual Mathematics
    (ref: cite:f.08_concep)
*** Algebra
    (ref: cite:saunders88_algeb)
*** Topoi: the Categorial Analysis of Logic
    (ref: cite:robert06_topoi)

* Have Read
  Texts in this list are read to my satisfaction /for the moment/. They are
  liable to move back to one of the other lists.

** Feel the Heat: An Embodied Approach to the Instruction of the Greenhouse Effect
   By Ian Thacker (Not yet published)
   <2018-04-27 Fri>

   Motto: "Perceptual inferences become causal rules"
** Consistent Overhead Byte Stuffing
   (ref: cite:cheshire1999consistent)
   <2018-04-24 Tue>

** A Theory of the Learnable
   (ref: cite:valiant84_theor_learn)
   <2018-04-18 Fri>
   [[file:reading-notes/valiant-a-theory-of-the-learnable.org][Notes]]
** The Marx and Engels Reader
   (cite:tucker78_marx_engel)
  [[file:reading-notes/marx-engles-reader.org][Notes]]
*** Chapters read
    - "Marx on the History of his Opinions"
    - "Discovering Hegel"
    - "To Make the World Philosophical"
    - "For a Ruthless Criticism of Everything Existing"
** The Inoperative Community
   (cite:peter01)
   [[file:reading-notes/nancy-the-inoperative-community.org][Notes]]
*** Chapters read

    - "The Inoperative Community"
    - "Literary Communism"



bibliography:~/Dropbox/bibliography/references.bib
