#+TITLE: Reading List

This page documents things I have read (since <2018-04-08 Sun>), and what I
intend to read.

* Have Read

** The Inoperative Community
   (Ref: cite:peter01)

   I've read the following chapters:

   - "The Inoperative Community"
   - "Literary Communism"

   It has got me me thinking about the possibility of a "computational
   communism" or, perhaps better, a "programmatical communism".

   It's not entirely clear to me what this would be, but its possibility is
   given by the fact that Nancy includes proofs as a form of literature --

   #+BEGIN_QUOTE
   Literature interrupts itself: this is, essentially, what
   makes it literature (writing) and not myth. Or better, what interrupts itself
   — discourse or song, gesture or voice, narrative or proof — /that/ is
   literature (or writing). Precisely what interrupts or suspends its own
   /mythos/ (that is to say, it’s *logos*). (page 72)
   #+END_QUOTE

   -- and the Curry-Howard analogy gives us programs as proofs.

   Something speaks to me in the way Nancy renders the concept of community, and
   the notion of the interruption of myth. (Myth includes the logos of origin
   (foundations) and destiny (pre-ordained purpose).)

* Will Read


  bibliography:~/Dropbox/bibliography/references.bib
