#+title: Iron Galaxy

WIP, and at the level of rough notes.

* Caveat

This is an inchoate, [[https://en.wikipedia.org/wiki/Divination][divinatory]] reading of Cannibal Ox's masterpiece [[https://en.wikipedia.org/wiki/The_Cold_Vein]["Iron
Galaxy"]]. Is sprawls thru semiotic constellations that spin out from the
lyrics. It is not meant to eclipse or delimit the authorial intent.

[[https://genius.com/Cannibal-ox-pigeon-lyrics][Pigeon]] and [[https://genius.com/Cannibal-ox-scream-phoenix-lyrics][Scream Pheonix]] are necessary companion songs.

* Text of the Lyrics

#+begin_src
"I feel like everybody wants something from me"
"Yeah tell me about it, it's a cold world out there
Sometimes I think I'm getting a little frosty myself"

My shell, mechanical found ghost
But my ghetto is animal found toast
My shell, mechanical found ghost
But my ghetto is animal found toast
My shell, mechanical found ghost
But my ghetto is animal found toast
Animal found toast
But my ghetto
Animal

Life's ill, sometimes life might kill
Vordul Mega, five digits grab mics, mic strike type ill
Is life real? Yo akh' he builds
When life feels like Earth don't spin, whirlwinds might blend
Life's at a standstill, dangerous cause man kills
And still cats visualize life ghetto like
One mind, sometime these cats see life
Street life in complete light and be like
I'm a live life after this one crime
One line from the Megalah blow spines
Everyone knows the city's ill, cats kill
Still black man holds nine, Gotta chill star C-A.L.L.A.H
Be the light of Shamar, work hard Shamar C-Cipher-A.L.L.A.H
Adapt bars snatch stars and detach large channels
But our bar's handle might, break mics
Vordul Megalah the cannibal ate mics
Strive, live live
Fuck five, I want a hundred and eight mics

Son, yo son did you see that kid yo?
Yo, yo, chill out man, chill out
Yo son did you, yo son he pulled it out"

Five digits cock biddy nine milli
One floor shot silly, spun city one verse hit milly
Little girls spinning curls three sixty, living in a world shitty
Yo they spun young earth, now shitty
NY 5-0 might shoot black head
Nigga sorry I sold space suit to crack head
DTs operate mechanically, po-po in slow-mo
Black kids locked away, add a key
Plus one fourth pound of smoke flow
While lock head Fabian, Ahmed Arabian, laying in
Bodeg holding drama AK, spoke like As-salamu OK
Choking vodka mixed with OJ
Wig splits mad quick
Spinning three six O wave, C4 blew the door
Number eight, Summer face tank top with a knot
Number nine said run the place
Took my girl stereo, CD, plus the tape
Brooke star, don't wet that, fucked her face lets stuff the place
Jet back to Santa Cruz, Californ-i-a
Peace to C-God locked up, cat born nine ways
Come home mad soon, live ill, life phases
Like little black girl got shot
Damn it hurts when they spun earth filled with knots
Gonna make a difference so we get locked
Caught in the shit and losing what we got
Come on black equals, equals

"Do you know that you're one of the few predator species
That preys even on itself?"

And if there's crack in a basement

Crack heads stand adjacent
Anger displacement from food stamp arrangements
You were a still born baby, mother didn't want you
But you were still born
Boy meets world, of course his pops is gone, what you figure
That chalky outline on the ground is a father figure?
So he steps to the next stencil, that's a hustler
Infested with money and diamond cluster
Let's talk in layman terms
Rotten apples and big worms, early birds and poachers
New York is evil at its core, so those who have more than them
Prepare to be victims
Ate up by vultures, the politicians
In a dog eat dog culture, that'll sick 'em
Lack of mineral, we take it personal
A pigeon can't drop shit if it never flew
Every day is no frills, empty krills
Broken 40 bottles and MCs with skills
I rest my head on 115
But miracles only happen on 34th, so I guess life is mean
And death is the median
And purgatory is the mode that we settle in (no doubt)
I've got that Eve's Bayou sense of touch
So I fought, to touch every hand of a fan to read their thoughts
Battered wives, molested children
Roaches on the floor, rats in the ceiling
Cats walk around New York with two fillings
One is in their mouth, the other does the killing
I'm Vast Aire, Kramer, top billing

(Yo rest in peace to Big L, 139)
#+end_src

Iron Galaxy Lyrics as written by Shamar Eugene Gardner Jaime Meline

Lyrics © CONCORD MUSIC PUBLISHING LLC

* Topical Gatherings

#+begin_src
With Cannibal Ox, the Iron Galaxy is a physical and psychic presence: “A hard
surrounding,” says Vast, “A way to play with the rock and a hard place… We said
fuck a rock this shit is cast iron. We’re in between a piece of iron and the
galaxy… (it) expresses our hood, our country, us being black men, growing up
urban inner city youth in America, in New York, in the East coast. We wanted one
phrase, and it was like… Iron Galaxy, that’s it.”

For Dick and Can Ox, iron is entrapment. A closing in. Something to endure,
battle against, or be destroyed by.
#+end_src

-- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/

** Still life


Vast

#+begin_src
Anger displacement from food stamp arrangements
You were a still born baby, mother didn't want you
But you were still born
Boy meets world, of course his pops is gone, what you figure
That chalky outline on the ground is a father figure?
#+end_src

Vordal

#+begin_src
When life feels like Earth don't spin, whirlwinds might blend
Life's at a standstill, dangerous cause man kills
And still cats visualize life ghetto like
One mind, sometime these cats see life
Street life in complete light and be like
I'm a live life after this one crime
One line from the Megalah blow spines
Everyone knows the city's ill, cats kill
Still black man holds nine, Gotta chill star C-A.L.L.A.H
#+end_src

The "still cats" are "still born": born into "lives at a standstill". In it
"these cats see" "in complete light" "street life": "life ghetto-like" "feels
like Earth don't spin" and presents the danger of "whirlwinds" that "might blend
life". A ghetto-like life renders man in a still life, where the spin of the
Earth in the cosmos can't be felt, perhaps in part because the "complete light"
of the "street light" will "snatch stars" from the sky. Thus the "still black
man" who "holds nine", who should "chill, star-see (C)". Indeed, C is to
understand, to see in the [[https://fivepercenterlessons.com/supreme-alphabet/][Supreme Alphabet]]:

#+begin_src
3. C-TO CEE-is to understand. At one time we couldn’t truly see the trick that was planted in our path because we had a mattress thrown over our eyes. But we’ve been born trice and know that we are Allah, the supreme eye that can see all. To see is to understand with the third eye which is the mind. Our two physical eyes are but doorways to the third eye which is the all seeing eye.
#+end_src

#+begin_src
On ‘AK-47’, Vordul is “tired of living trapped behind walls, we’d rather be
outside watching the stars, fuck living trapped behind bars, we gotta escape,
block’s hot as Mars.”
#+end_src

-- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/

** Allah

Vordul

#+begin_src
Still black man holds nine, Gotta chill star C-A.L.L.A.H
Be the light of Shamar, work hard Shamar C-Cipher-A.L.L.A.H
Adapt bars snatch stars and detach large channels
But our bar's handle might, break mics
Vordul Megalah the cannibal ate mics
Strive, live live
Fuck five, I want a hundred and eight mics
#+end_src

[[https://en.wikipedia.org/wiki/Star_and_crescent][Star C]] as the Star and Crescent?

** Meter and Numerology

Metrics are essential for the machine shell

#+begin_src
[Vordul] is steeped in the Nation of Gods and Earths – a group that splintered from The Nation Of Islam and whose followers are known as Five-Percenters. Here’s Vordul, child of Mecca (Harlem), hauled up on a mattress in Medina (Brooklyn),
#+end_src

-- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/


#+begin_src
The Nation teaches that Supreme Mathematics and Supreme Alphabet, a set of principles created by Allah the Father, is the key to understanding humankind's relationship to the universe
#+end_src

-- https://en.wikipedia.org/wiki/Five-Percent_Nation


#+begin_src
1. Cipher – 360 degrees consisting of 120 knowledge, 120 wisdom, 120 understanding. Zig-zag-zig. From knowledge to understanding, back to knowledge.
#+end_src

-- https://fivepercenterlessons.com/supreme-mathematics/

Vordul

#+begin_src
Still black man holds nine, Gotta chill star C-A.L.L.A.H
Be the light of Shamar, work hard Shamar C-Cipher-A.L.L.A.H
Adapt bars snatch stars and detach large channels
But our bar's handle might, break mics
Vordul Megalah the cannibal ate mics
Strive, live live
Fuck five, I want a hundred and eight mics
#+end_src

9: nine millie
[[https://en.wikipedia.org/wiki/108_(number)][108]]

Vast

#+begin_src
Broken 40 bottles and MCs with skills
I rest my head on 115
But miracles only happen on 34th, so I guess life is mean
And death is the median
And purgatory is the mode that we settle in (no doubt)
#+end_src

** Shell Machine Ghost

My shell: enclosure, protection.
Spirit-machine connection.

Vordal's verses here speak mostly to the shell.

** Ghetto Animal Toast

My ghetto: environment, surrounding, deprecating confinement
Animal-food conditioning.

Toast is food, but also a [[Gun][gun]]. "Animal found toast" is the man-animal getting
being made to take gun.

"Cannibal Ox" already signals the eating and being eaten of the animal.

An [[https://en.wikipedia.org/wiki/Ox][ox]] is

#+begin_src
a bovine, trained and used as a draft animal. Oxen are commonly castrated adult male cattle; castration inhibits testosterone and aggression, which makes the males docile and safer to work with.
#+end_src

But, [[https://medium.com/cuepoint/how-el-p-and-cannibal-ox-crafted-a-cult-classic-4d17ccb5a93b][on the name of the group]], they are recorded as saying

#+begin_src
Much like their vocabulary rich rhyme style, Vast and Vordul settled on the strange name of Cannibal Ox in a brainstorming session of “just throwing words in the air.” But as time progressed, the meaning of the Cannibal Ox name was given greater significance, representative of the battle scene they emerged from.

“Cannibal Ox came from us being lyrically sharp. That’s the base metaphor. All of this ‘blade’ talk comes from being in Harlem, and seeing dudes fight and spit razors. Then it got attached to cannibalism somehow, like we lyrically devour MCs. We have to feed on our own kind,” Vast explains. “The ‘Ox’ is the blade. What did Big L say on ‘Ebonics?’ ‘A blade is an ox.’”
#+end_src

Why is "ox" a blade, according to [[https://genius.com/13765][an annotation on rap-genius]]

#+begin_src
Almost certainly short for “box cutter”, or named after oxen, which are used to
plough fields in lines like razor blades are used to separate cocaine into
lines.

The definition of “ox” as “box cutter” can occasionally lead to
misinterpretations, such as when Nas raps

    “I heard you blew a nigga with an ox for the phone piece”

on “One Love”, which may have ironically inspired Big L to write this line.
Rather than being a euphemism for a blowjob, this line means that he heard his
friend cut someone up just to use the phone.
#+end_src

This is borne out by [[https://therightrhymes.com/ox/][the right rhymes]].

#+begin_src
Using the Supreme Alphabet, the name Cannibal Ox itself is embedded. O, meaning
cipher, X unknown.
#+end_src

-- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/

Vast's verses here speak more to the ghetto tho Vordul does offer:

#+begin_src
Life's at a standstill, dangerous cause man kills
And still cats visualize life ghetto like
One mind, sometime these cats see life
...
Adapt bars snatch stars and detach large channels
But our bar's handle might, break mics
Vordul Megalah the cannibal ate mics
#+end_src

Vast gives us

#+begin_src
Roaches on the floor, rats in the ceiling
Cats walk around New York with two fillings
...
Let's talk in layman terms
Rotten apples and big worms, early birds and poachers
New York is evil at its core, so those who have more than them
Prepare to be victims
Ate up by vultures, the politicians
In a dog eat dog culture, that'll sick 'em
Lack of mineral, we take it personal
A pigeon can't drop shit if it never flew
...
Cats walk around New York with two fillings
One is in their mouth, the other does the killing
#+end_src

The merging of the metallic blade, a tool-turned-weapon, and the domesticated
animal-turned-tool, perhaps castrated with its namesake blade. Slicing off a
part as a way to derive the domesticate animal from the violent utility of the
mechanical. The beast of burden who ploughs lines for the dominating animals
agriculture, an animal producing food for the animal that will eat it. We have
to feed on (and off) our own kind.

[[https://en.wikipedia.org/wiki/Krill][Krill]]:

- https://www.68to05.com/essays/2004-mf-doom-mm-food
- https://genius.com/Natural-elements-life-aint-fair-lyrics
- https://therightrhymes.com/krill/

Pigeon

#+begin_src
Metallic wing pigeon
Cannibal Ox
#+end_src

-- https://genius.com/Cannibal-ox-pigeon-lyrics

#+begin_src
Clay pigeons are discs of baked clay which are thrown into the air by a machine as targets for gun shooting practice.
#+end_src

https://www.collinsdictionary.com/dictionary/english/clay-pigeon

#+begin_src
This all culminates on ‘Pigeon’ and the once-secret ‘Scream Phoenix’. ‘Pigeon’
was Vordul’s idea, explains Vast in Bazooka Tooth. He was like “Yo, birds that
are at the bottom of the food chain, but yet they still survive, they still make
it.” Pigeon as an expression of bare-bone survival. This does have precedent in
hip hop. Just look at KMD on ‘Peachfuzz’, where Zev Love X (later MF DOOM) muses
“if I was a bird I’d be a pigeon…”, but never has it been fleshed out to such
poetic extent.
#+end_src

-- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/

** Gun

Aka [[https://therightrhymes.com/toast/]["toast"]]:

Pete Rock & CL Smooth:

#+begin_src
So back up, be ghost when I keep my toast, Murder She Wrote, yo
#+end_src

Gang Starr:

#+begin_src
One more false move, I'll grab my toast and I'll bust ya
#+end_src

Bullet shell:

#+begin_src
Vordul Mega, five digits grab mics, mic strike type ill
...
Still black man holds nine, Gotta chill star C-A.L.L.A.H
#+end_src

#+begin_src
("Yo son did you, yo son he pulled it out")
...
Five digits cock biddy nine milli
One floor shot silly, spun city one verse hit milly
...
NY 5-0 might shoot black head
...
Bodeg holding drama AK, spoke like As-salamu OK
...
Like little black girl got shot
#+end_src

Vast

#+begin_src
Ate up by vultures, the politicians
In a dog eat dog culture, that'll sick 'em
Lack of mineral, we take it personal
A pigeon can't drop shit if it never flew
...
Cats walk around New York with two fillings
One is in their mouth, the other does the killing
#+end_src

The gun as a machine that fills the soul hole, analogue to the metallic
prosthetic filling the hole in the damaged animal tooth. The gun is a
non-nourishing filling for the emptied shell of the ghosted mechanical self in
the sam way that toast is a non-nourishing filling for an empty animal belly.

** Spinning

#+begin_src
15. 0-CIPHER-is a person, place or thing which is complete within itself, for a cipher is a complete circle consisting of 360 degrees. The black woman is also a cipher because cipher means C-I-POWER-HER and surely God powers her by mastering her with his mind. Her-Power-You-Must-See in order to master her equality.
#+end_src
* References

- https://thequietus.com/opinion-and-essays/anniversary/cannibal-ox-el-p-philip-k-dick/
- https://medium.com/cuepoint/how-el-p-and-cannibal-ox-crafted-a-cult-classic-4d17ccb5a93b
- https://fivepercenterlessons.com/supreme-alphabet/
- https://fivepercenterlessons.com/supreme-mathematics/
