#+TITLE: Day 7: Weekend 1.2
#+DATE: <2019-09-29 Sun>

* Today's Progress
Our Surfing adventure this morning knocked me out for the rest of the day, and I
only managed to accomplish a tiny optimization on my blogging flow. We had a
blast tho, and I'm going to bed absurdly early, so I should be starting the
week out relaxed andfully recharged.

** Tooling
=org-publish= was taking an absurd amount of time to publish updates. [[https://bastibe.de/2014-05-07-speeding-up-org-publishing.html][Bastion
Bechtold's note]] describing how they diagnosed and fixed a similar slowdown
helped guide me. The main trick was running the profiler to reveal what was
causing the slowdown:

#+BEGIN_SRC emacs-lisp
(progn (profiler-start 'cpu) (function-to-profile) (profiler-report))
#+END_SRC

After fixing the cause of the slowdown, the time needed to publish these org
files to HTML is down by at least 75%.

* Tomorrow's Program

- Finish CH. 2 of cite:rob2014type
- Add type checking to themis' simply typed lambda calculus
- Start CH. 3 cite:rob2014type
- Dig in to fixing the 1ML type-checking bug on pairs

bibliography:~/Dropbox/bibliography/references.bib
