#+TITLE: Day 20: This, That, and These
#+DATE: <2019-10-12 Sat>

#+BEGIN_QUOTE
Composing signs from other signs is a fundamental strategy for managing the
complexity of non-trivial communication, regarding complex signs at one level as
individual signs at a higher level.

(cite:goguen1998introduction, 3)
#+END_QUOTE

* Today's Progress

** PLT
- Finished implementing all the most generally useful parts of =Data.These= and
  =Data.Align= in OCaml.
- I spent some time researching, thinking, and taking notes on a semiotic analysis of
  位-calculus. The ultimate aim of this line of thinking is to see if I can use
  Goguen's methodology of algebraic semiotics (see cite:goguen1998introduction)
  to represent type systems as "semiotic morphisms" from the untyped 位-calculus.
  This follows a suspicion that, for type systems on the left side of the 位-cube
  (where types never depend on terms) type systems can be understood as
  /interfaces/ to the 位-calculus. (This must, naturally, proceed on a view
  typing ala-Curry, since in the Church approach the typing is embedded in the
  lambda terms).

* Tomorrow's Program

** PLT
Write the test suite for the OCaml port of =These= and the nascent =Alg= library,
providing algebraic data structures.

** Writing
Spend some time collecting my thoughts on the speculative
convergence of semiotics (in the tradition of Peirce advaced by Goguen) with
some of Girard's writing in cite:girard11 and the concern with communication and
community in Nancy's cite:peter01.

bibliography:~/Dropbox/bibliography/references.bib
