#+TITLE: Lightweight Webapps in OCaml

This tutorial aims to guide those familiar with OCaml, into one possible
approach for a lightweight webapp backend. The app is lightweight in that it
doesn't take much code to define and in that it probably shouldn't be used for
heavy, industrial applications.

(The OCaml ecosystem also has great support for the frontend, thanks to
=Js_of_ocaml= and =Bucklescript=, but we'll save that for a followup.)

* Dependencies

We will be using the following OCaml libraries:

- [[https://opam.ocaml.org/packages/core/][Core]]: A standard standard library alternative
- [[https://opam.ocaml.org/packages/opium/][Opium]]: A Sinatra-like web toolkit
- [[https://github.com/paurkedal/ocaml-caqti][Caqti]]: For interfacing with PostgreSQL
- [[https://opam.ocaml.org/packages/tyxml/][TyXML]]: A library for generating correct HTML

There are many other excellent and powerful web libraries we won't be using. See
[[https://ocamlverse.github.io/content/web_networking.html][the OCamlverse page on Web and Networking]] for a catalog.

* Prerequisites

This section is for readers who don't currently have a well configured OCaml
setup in place. Skip to the [[Setup][next]] if you're already setup with the modern suite
of tools.

** 1. Install and configure opam (the OCaml package manager)

To install opam, run

#+BEGIN_SRC sh
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
#+END_SRC

or [[https://opam.ocaml.org/doc/Install.html][choose another method.]]

Initialize opam and build your main working environment with

#+BEGIN_SRC sh
opam init
# Install any dependencies called for
# Answer yes to the prompts to configure your shell environment

opam switch 4.08.1
# Sets the system ocaml compiler to use ocaml 4.08.1
# Use a different version at your own discretion
#+END_SRC

** 2. Install editor support and initialize your configurations

For the basic tooling, run

#+BEGIN_SRC sh
opam install user-setup merlin ocamlformat ocp-indent
opam user-setup install
#+END_SRC


*** Emacs

#+BEGIN_SRC sh
opam install tuareg
#+END_SRC

If you aren't already an emacs user but want to give it a spin, I highly
recommend the [[https://www.spacemacs.org/][spacemacs]] distribution for a beginner friendly approach.

I use doom-emacs, and find the IDE experience phenomenal.

*** For Vim or VSCode

See [[https://ocamlverse.github.io/content/editor_support.html][recommendations on the OCamlveres]].

* Setup

* TODO Corrections, Suggestions, and Feedback

If you have any questions or feedback, please feel free to

- TODO Make a PR to correct or improve something on this page
- TODO Open an issue
- Contact me via [[http://shonfeder.net][my homepage]].
