#+TITLE: Notes on The Inoperative Community

(cite:peter01)

* Community

Nancy tries to describe the possibility of *an intrinsically anti-totalitarian
community*. This would be a way of being together which is not subordinated to
any totalizing idealogy, whether of race, nation, individualism, collectivism,
expansion,  domination of nature, utilitarian calculation, techno-theo-logico
transcendence, etc.

How would we articulate the possibility of such community? It resists
summarization[fn:summary], but the passage I've found most evocative and
perspicuous is the following. Here, Nancy differentiates /community/ from
/organization/:

#+BEGIN_QUOTE
Organic totality is a totality in which the reciprocal articulation of the parts
is thought under the general law of an instrumentation which cooperates to
produce and maintain the whole as form and final reason of the ensemble (at
least this is the way the "organism" has been conceived since Kant: it is not
obvious that a living body is to be thought only according to this model).
Organic totality means the totality of the operation as means and of the work as
end. But the totality of community--by which I understand the totality of
community resisting its own setting to work--is a whole of articulated
singularities. Articulation does not mean organization. It refers neither to the
notion of instrument nor to that of operation or work. Articulation has nothing
to do, as such, with an operative system of finalities--although it can no doubt
always be related to such a system or be integrated into it. By itself,
articulation is only a juncture, or more exactly the play of the juncture: what
takes place where different pieces touch each other without fusing together,
where they slide, pivot, or tumble over one another, one at the limit of the
other--exactly at its limit--where these singular and distinct pieces fold or
stiffen, flex or tense themselves together and through one another, unto one
another, without this mutual /play/--which always remains, at the same time, a
play /between/ them--ever forming into the substance or the higher power of a
Whole. Here, /the totality is itself the play/ of the articulations. This is why
a whole of singularities, which his indeed a whole, does not close in around the
singularities to elevate them to its power: the whole is essentially the opening
of the singularities in their articulations, the tracing and the pulse of their
limits. (76)
#+END_QUOTE

Imagine a way of being together, of being in community, in which that
togetherness cannot eclipse or subordinate those who gather, because "the
totality is itself the play" of the articulations that differentiate each from
the other (and connect each to the other). Imagine a community which is
"essentially the opening of the singularities in their articulations, the
tracing and the pulse of their limits."

* Communication

#+begin_quote
Community means, consequently, that there is no singular being without another
singular being ... that there is no communion of singularities in a totality
superior to them and immanent to their common being.

In place of such a communion there is communication. Which is to say, in very
precise terms, that finitude itself /is/ nothing; it is neither a ground, nor an
essence, nor a substance. But it appears, it presents itself, it exposes itself,
and thus it /exists/ as communication. In order to designate this singular mode
of appearing, this specific phenomenality, which is no doubt more originary than
any other (for it could be that the world appears to the community, not the
individual), we would need to be able to say that finitude /co-appears/ or
/compears/ (com-paraît) and can only /compear/: in this formulation we would
need to hear that finite being always presents itself "together", hence
severally; for finitude always presents itself in being-in-common and as this
being itself, and it always presents itself at a /hearing/ and before the
judgment of the law of community, or, more originarily, before the judgment of
the community as law.

Communication consists before all else in this sharing and in this compearance
(com-parution) of finitude: that is, in the dislocation and in the
interpellation that reveal themselves to be constitutive of being-in-common --
precisely inasmuch as being-in-common is not a common being. The finite-being
exists first of all according to a division of sites, according to an
extension -- /partes extra partes/ -- such that each singularity is extended (in
the sense that Freud says: "The psyche is extended"). It is not enclosed in a
form -- although its whole being touches against its singular limit -- but it is
what it is, singular being (singularity of being), only through its extension,
through the areality that above all extroverts it in its very being -- whatever
the degree or the desire of its "egoism" -- and that makes it exist only by
/exposing it to an outside/. This outside is in its turn nothing other than the
exposition of another areality, of another singularity -- the same other. This
exposure, or this exposing-sharing, gives rise, from the outset, to a mutual
interpellation of singularities prior to any address in language (though it
gives to this latter its first condition of possibility). Finitude compears,
that is to say it is exposed: such is the essence of community.

(29)
#+end_quote

* Literature

We see an image of such community take shape in reciprocal, responsive,
rupturing dialogue. The word "rupture" indicates a dialogue which is not a
mechanical convergence upon a predestined agreement, but rather an interplay of
saying and remaining silent that is transformative. In such dialogue, the
communicating exposes each to the other: "each one articulated upon itself or in
itself, facing the other, at the limit of itself and of the other". In such
dialogue, there can be rupture, transformation--"tracing" and "pulse" of our
limits--because each saying is prepared to interrupt itself to make room for
receiving what the other has to say, and how the other is in their saying.

#+BEGIN_QUOTE
Dialogue, this articulation of speech, or rather this sharing of voices is, in
the sense I am trying to communicate, "literature".
#+END_QUOTE

For Nancy, in this work, "literature" is the name for communication which
interrupts itself, and in so doing makes room for the space to receive the
transformation of the other. Literature, the "writing that interrupts itself",
is communication that limns the countours of the singular beings who are
together in community.

#+BEGIN_QUOTE
Literature interrupts itself: this is, essentially, what makes it literature
(writing) and not myth. Or better, what interrupts itself — discourse or song,
gesture or voice, narrative or proof — /that/ is literature (or writing).
Precisely what interrupts or suspends its own /mythos/ (that is to say, it’s
*logos*). (72)
#+END_QUOTE

[[../themata/programming/index.org][Programming]] is a form of writing. Can it be a form of literature? Given
[[http://www.scholarpedia.org/article/Computational_type_theory#Proofs][types-as-propositions/programs-as-proof]], where

#+BEGIN_QUOTE
... the proof of the goal can be seen as creating a program to compute a
function meeting a certain specification. We say that the proof acts as a
program. This proofs-as-programs principle is a consequence of the propositions
as types principle.
#+END_QUOTE

we get programs as a form of proof, which is a form of literature. Imagine
programs that interrupt themselves, that invite--far beyond mere
interaction--/intervention/ from those who write/read/run them. Think on the
possibility of a "computational communism" or, perhaps better, a "programmatical
communism".

bibliography:~/Dropbox/bibliography/references.bib

* Footnotes

[fn:summary] It resists summarization because a summary encapsulates the
totality ([[https://www.etymonline.com/word/summary][/summa/]]) of the subject in an abbreviated form, but the point of the
inoperable (more literally "unworking" or "idle") community is that there are
not short cuts to its totality: it is whole only in the irreducible and
ungeneralizable articulation of each singular part.
