#+TITLE: Notes on /An Introduction to Mathematics/
Whitehead, A. N., An introduction to mathematics (1993), : Oxford University Press.

* Excerpts
** On the economy of sign systems                                  :notation:

   #+NAME: whitehead93#1
   #+BEGIN_QUOTE
   Mathematics, as a science commenced when first someone, probably a Greek,
   proved propositions about /any/ things or about /some/ things, without
   specification of definite particular things.
   ...
   Perhaps it required the introduction of the arabic numerals, by which the use
   of letters as standing for definite numbers has been completely discarded in
   mathematics, in order to suggest to mathematicians the technical convenience
   of the use of letters for the ideas of /any/ number and /some/ number.
   #+END_QUOTE

   As an aside, I note two specious claims:

   1. Stuff fitting the name "mathematics" surely predates the Greeks, and
      Whitehead's characterization of the first mathematical activities seem to
      bear the unmistakable mark of logicist's bias.
   2. There are still letters used to refer to some definite numbers, e.g., \( e
      \).

** TODO Notation as Aid to Efficiency of Thought   :notation:thought:writing:

   #+NAME: whitehead93#2
   #+BEGIN_QUOTE
   ... the enormous importance of good notation. By relieving the brain of
   all unnecessary work, a good notation sets it free to concentrate on more
   advanced problems, and in effect increases the mental power of the race. (39)
   #+END_QUOTE

   Writing *inscription* is an intellectual prosthetic. It is so in the
   shallower, more obvious sense that it can be used to extend memory by
   recording information externally, and in innumerable deeper senses:

   - Notation organizes, concentrates, accelerates thought
   - The logic of inscriptions is reinscribed in our thought, amplifying
     reflectivity
   - The externalization and objectification of concepts forces a dialectical
     process that refines and sharpens understanding
   - The communication of thought through beings causes world and
     consciousnessness to interpenetrate, weaving together community at the
     limiting points of alterity. (Nancy's "Literary Communism").


   #+NAME: whitehead93#3
   #+BEGIN_QUOTE
   ...by the aid of symbolism we can make transitions in reasoning almost
   mechanically by the eye, which otherwise would call in to play the higher
   faculties of the brain.

   It is a profoundly erroneous truism, repeated by all ....
   #+END_QUOTE
   
