#+TITLE: A List of Leftist Tech Companies

This is a list of tech companies which are explicitly pursing systemic change
to advance solidarity, climate justice, and equitable social systems.

I haven't been able to find a list of this sort, so I've started making my own.

* [[https://github.com/hng/tech-coops][List of Tech Coops]]

#+BEGIN_QUOTE
A list of tech coops and resources concerning tech coops and worker owned cooperatives in general.
#+END_QUOTE

* [[https://positiondev.com/][Position Development]]

#+BEGIN_QUOTE
a worker-run software development company with a focus on independent media,
cultural institutions and socially minded organizations." (Their client list
includes Verso and Haymarket books).
#+END_QUOTE

* [[https://riseup.net/][Riseup]]

#+BEGIN_QUOTE
Riseup provides online communication tools for people and groups working on
liberatory social change. We are a project to create democratic alternatives and
practice self-determination by controlling our own secure means of
communications.
#+END_QUOTE

* [[https://techworker.coop/][Tech Co-op Network]]

#+BEGIN_QUOTE
North American Technology Worker Cooperatives
#+END_QUOTE
