#+TITLE: A List of Leftist Tech Companies and Organizations

(Including lists of lists of such companies.)

This is a list of tech companies and organizations which are explicitly pursing
systemic change to advance solidarity, climate justice, and equitable social
systems.

I couldn't find a list of this sort easily, so I've started making my own. In
the process, I've found some similar lists, so they go on this list as well.

* [[https://www.andalsotoo.net/][And Also Too]]

#+BEGIN_QUOTE
A collaborative design studio for social justice visionaries
#+END_QUOTE

* [[https://agaric.coop/][Agaric]]

#+BEGIN_QUOTE
We are Agaric, a worker-owned cooperative. We build websites and online tools
that respect your freedom. We provide training and consultation to meet your
goals.
#+END_QUOTE

* [[https://autonomic.zone/][Autonomic]]

#+begin_quote
Autonomic is a hive mind of 13 people around the world turning gentle chaos into
websites, infrastructure and design. We share 1 email inbox, we make decisions
using consensus and we all get paid the same.
#+end_quote

* [[https://coopcloud.tech/][Co-op Cloud]]

#+begin_quote
Co-op Cloud is a software stack that aims to make hosting libre software
applications simple for small service providers such as tech co-operatives who
are looking to standardise around an open, transparent and scalable
infrastructure. It uses the latest container technologies and configurations are
shared into the commons for the benefit of all.
#+end_quote

* De[[https://designjustice.org/][sign Justice Network]]

#+BEGIN_QUOTE
an international group of people and organizations committed to rethinking
design processes so they center people who are often marginalized by design
#+END_QUOTE


* [[https://github.com/hng/tech-coops][List of Tech Coops]]

#+BEGIN_QUOTE
A list of tech coops and resources concerning tech coops and worker owned cooperatives in general.
#+END_QUOTE

* [[https://positiondev.com/][Position Development]]

#+BEGIN_QUOTE
a worker-run software development company with a focus on independent media,
cultural institutions and socially minded organizations." (Their client list
includes Verso and Haymarket books).
#+END_QUOTE

* [[https://riseup.net/][Riseup]]

#+BEGIN_QUOTE
Riseup provides online communication tools for people and groups working on
liberatory social change. We are a project to create democratic alternatives and
practice self-determination by controlling our own secure means of
communications.
#+END_QUOTE

* [[https://techworker.coop/][Tech Co-op Network]]

#+BEGIN_QUOTE
North American Technology Worker Cooperatives
#+END_QUOTE

* [[https://utaw.tech/about/][UTAW]]

#+begin_quote
United Tech and Allied Workers is a branch of the Communication Workers Union
which seeks to represent and fight for workers interests in the tech industry.
#+end_quote
